### ISSUE TITLE
How can I do this??? load specific page.

### ISSUE THREAD

**Issue by digitxo** [eighty20results/pmpro-rest-api#3]
Hi. I managed to get the getUserMembershipLevel example successfully. I also managed to use JWT-AUTH to receive an auth token for a user. Currently I use PMPro to grant my users access to

http://www.mywebpage.com/pmpro-stuff/<USERNAME>

Where <USERNAME> is the UN they logged in with.

I'd like to access this page in JSON format with REST API for my iOS app.

Is it possible to do this with JWT-AUTH? Will I need only PMPro endpoints? How can I go about this! Thank you for help.

**Comment by eighty20results** [comment]
This rest API should let you check that the logged in user is supposed to have access to the page by calling the `/pmpro/v1/hasaccess/<post_or_page_id>/<user_id>` endpoint.

This plugin doesn't explicitly verify that the user ID in question is logged in, but that isn't necessary for the `hasaccess` endpoint since the underlying `pmpro_has_membership_access()` function will return false if the user isn't logged in and you query the endpoint w/a PMPro specific page/post ID.

Thus, the safest thing to do is to first check if they have access via the `hasaccess` endpoint and then try to get the page using the standard WordPress REST API endpoints for posts/pages.

However I _think_ the WP REST API itself could also return an error if you simply tried to grab the page w/a user who doesn't have a valid membership.

**Comment by digitxo** [comment]
> This rest API should let you check that the logged in user is supposed to have access to the page by calling the `/pmpro/v1/hasaccess/<post_or_page_id>/<user_id>` endpoint.
> 
> This plugin doesn't explicitly verify that the user ID in question is logged in, but that isn't necessary for the `hasaccess` endpoint since the underlying `pmpro_has_membership_access()` function will return false if the user isn't logged in and you query the endpoint w/a PMPro specific page/post ID.
> 
> Thus, the safest thing to do is to first check if they have access via the `hasaccess` endpoint and then try to get the page using the standard WordPress REST API endpoints for posts/pages.
> 
> However I _think_ the WP REST API itself could also return an error if you simply tried to grab the page w/a user who doesn't have a valid membership.

Thank you for your response. My question is this, I'm using PMPro to give my members "individual pages." These are at the url https://balancingpawsdogtraining.com/users-page/digit/ if the username is digit. How can I find the post or page id for this username? Dynamically, incase another user is being used.

**Comment by eighty20results** [comment]
> How can I find the post or page id for this username? 

PMPro uses WordPress for everything except the functionality to determine whether or not a page is a membership protected page. I.e. standard WordPress post/page/user endpoints apply for the REST API and there are a lot of sources online for best practices/how to go about getting this info

> Dynamically, incase another user is being used.

You'd probably have to know the user's `user_login`, then use the standard WordPress `pages` endpoint with the [appropriate arguments](https://wordpress.stackexchange.com/questions/257505/how-do-you-retrieve-a-post-by-slug-name-through-rest-api).
